-- MySQL Script generated by MySQL Workbench
-- Tue Aug  8 17:52:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bingehive_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bingehive_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bingehive_db` DEFAULT CHARACTER SET utf8 ;
USE `bingehive_db` ;

-- -----------------------------------------------------
-- Table `bingehive_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bingehive_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `first` VARCHAR(255) NOT NULL,
  `last` VARCHAR(255) NOT NULL,
  `pic` VARCHAR(255) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bingehive_db`.`list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bingehive_db`.`list` (
  `list_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `list_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`list_id`),
  INDEX `fk_list_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_list_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bingehive_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bingehive_db`.`list_entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bingehive_db`.`list_entry` (
  `entry_id` INT NOT NULL AUTO_INCREMENT,
  `list_id` INT NOT NULL,
  `id` VARCHAR(255) NOT NULL,
  `backdrop_path` VARCHAR(255) NOT NULL,
  `original_title` VARCHAR(255) NOT NULL,
  `overview` TEXT(2000) NOT NULL,
  `rating` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`entry_id`),
  INDEX `fk_list_entry_list1_idx` (`list_id` ASC) VISIBLE,
  CONSTRAINT `fk_list_entry_list1`
    FOREIGN KEY (`list_id`)
    REFERENCES `bingehive_db`.`list` (`list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
